# Project Information
site_name: PagerDuty Incident Response Documentation
site_description: A collection of information about the PagerDuty incident response process. Not only how to prepare new employees for on-call responsibilities, but also how to handle major incidents, both in preparation and after-work.
site_author: PagerDuty, Inc.
site_url: https://response.pagerduty.com/

# Repository
repo_name: 'GitHub'
repo_url: https://github.com/juju4/incident-response-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: 'pagerduty'
  title: 'Incident Response'

extra_javascript:
  - 'js/github_forks.js'
  - 'js/mermaid.min.js'
# Set default cover image
extra:
  cover: assets/img/covers/default.png

# Theme overrides and customizations for this specific site.
extra_css: ['assets/css/custom.css']

# Contents
nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - On-Call:
    - Being On-Call: 'oncall/being_oncall.md'
    - Who's On-Call?: 'oncall/whos_oncall.md'
    - Alerting Principles: 'oncall/alerting_principles.md'
  - Before an Incident:
    - What is an Incident?: 'before/what_is_an_incident.md'
    - Confidentiality Levels: 'before/confidentiality_levels.md'
    - Severity Levels: 'before/severity_levels.md'
    - Different Roles: 'before/different_roles.md'
    - Call Etiquette: 'before/call_etiquette.md'
    - Communication Channels: 'before/communication_channels.md'
    - Complex Incidents: 'before/complex_incidents.md'
    - PGP/GPG Key Management: 'before/pgp_key.md'
    - Resources: 'before/resources.md'
  - During an Incident:
    - During an Incident: 'during/during_an_incident.md'
    - Security Incident: 'during/security_incident_response.md'
    - Security - BGP Hijacking: 'during/bgp_hijacking.md'
    - Security - DDoS: 'during/ddos.md'
    - Security - DNS Cache Poisoning: 'during/dns_poisoning.md'
    - Security - Phishing: 'during/phishing.md'
    - Security - Social Engineering: 'during/social_engineering.md'
    - Security - Suspicious System: 'during/suspicious_system.md'
    - Security - Compromised cloud credentials: 'during/cloud_credentials_compromised.md'
    - Security - 3rd party compromised: 'during/3rdparty_compromised.md'
  - After an Incident:
    - After an Incident: 'after/after_an_incident.md'
    - Post-Mortem Process: 'after/post_mortem_process.md'
    - Post-Mortem Template: 'after/post_mortem_template.md'
    - Effective Post-Mortems: 'after/effective_post_mortems.md'
    - Postmortem Process: 'after/post_mortem_process.md'
    - Postmortem Template: 'after/post_mortem_template.md'
    - Effective Postmortems: 'after/effective_post_mortems.md'
    - Metrics: 'after/metrics.md'
  - Training:
    - Overview: 'training/overview.md'
    - Incident Commander: 'training/incident_commander.md'
    - Deputy: 'training/deputy.md'
    - Scribe: 'training/scribe.md'
    - Subject Matter Expert: 'training/subject_matter_expert.md'
    - Customer Liaison: 'training/customer_liaison.md'
    - Internal Liaison: 'training/internal_liaison.md'
    - Security incidents: 'training/security_incidents.md'
    - Glossary: 'training/glossary.md'
  - Training Courses:
    - Incident Response: 'training/courses/incident_response.md'
  - Additional Resources:
    - Reading: 'resources/reading.md'
    - ChatOps: 'resources/chatops.md'
    - Anti-Patterns: 'resources/anti_patterns.md'
    - Email Investigation: 'resources/email_investigation.md'
    - File Investigation: 'resources/file_investigation.md'
    - Subject Access Request: 'resources/subject_access_request.md'
  - About: 'about.md'

# Analytics
google_analytics: ['UA-XXX-X', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
